# Site config
title: "Marco Botto: JavaScript/ES6, React and Angular enthusiast"
description: "Articles on JavaScript/ES6, React and Angular."
author: Marco Botto
email: info@marcobotto.com
url: "http://marcobotto.com"
baseurl: ""

# Sites config
github: elboman
twitter: elboman
linkedin: elboman
disqus: marcobotto
google_analytics: UA-71636045-1

# Jekyll config
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
permalink: /:year/:month/:title
paginate: 6
paginate_path: "page:num"

# Build config
sass:
    compressed: true
gems: [jekyll-paginate, jekyll-gist]