# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
permalink: /:year/:month/:title
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true
sass:
    compressed: true


# edit here to achieve your personal greatness
url: "http://marcobotto.com"
baseurl: "/"
title: Marco Botto
author: Marco Botto
description: Personal blog
avatar: profile.jpg
email: info@marcobotto.com
github: elboman # username
twitter: elboman
linkedin: elboman
#stackoverflow: elboman   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: marcobotto
google_analytics: UA-71636045-1


# needed for travis-ci build
exclude: [vendor]
